[package]
name = "exploit-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "2.0.1"
common = { path = "../common" }
deadpool-lapin = "0.11.0"
diesel = { version = "2", features = ["postgres", "uuid", "r2d2", "chrono"] }
dotenv = "0.15"
env_logger = "0.10"
futures-util = "0.3.30"
lapin = "2.3.1"
lazy_static = "1.4.0"
log = "0.4.17"
nix = { version = "0.27.1", features = ["process", "signal"] }
num_cpus = "1.15.0"
rand = "0.8.5"
scopeguard = "1.1.0"
serde = "1.0.152"
tokio = "1.24.1"
uuid = { version = "1", features = ["v4", "serde"] }
