- name: Setup variables
  hosts: all
  tasks:
    - name: Setup private ips
      ansible.builtin.set_fact:
        livectf_database_ip: "{{ hostvars[groups['database'][0]].private_ip }}"
        livectf_rabbitmq_ip: "{{ hostvars[groups['rabbitmq'][0]].private_ip }}"
        livectf_web_ip: "{{ hostvars[groups['web'][0]].private_ip }}"
        livectf_registry_ip: "{{ hostvars[groups['registry'][0]].private_ip }}"
        livectf_redis_ip: "{{ hostvars[groups['redis'][0]].private_ip }}"
        livectf_monitor_ip: "{{ hostvars[groups['monitor'][0]].private_ip }}"
        web_static_ip: "[REDACTED]" # TODO (P3): GEt this dynamically from Terraform output instead

- name: Set paranoid level
  hosts: runner
  tasks:
    - ansible.posix.sysctl:
        name: kernel.perf_event_paranoid
        value: '-1'
        state: present
